INSERT INTO Data.MeasurementUnit(Name)
VALUES
    ('whole'),
    ('c.'),
    ('tbsp.'),
    ('tsp.'),
    ('gallon'),
    ('qt.'),
    ('oz.'),
    ('pt.'),
    ('half'),
    ('dash'),
    ('g.'),
    ('kg.'),
    ('can'),
    ('box'),
    ('pkg.'),